require 'httparty'

potter_chars =[
  { fname: 'Euan', lname: 'Abercrombie', house_id: 1},
  { fname: 'Katie', lname: 'Bell', house_id: 1},
  { fname: 'Sirius', lname: 'Black', house_id: 1},
  { fname: 'Lavender', lname: 'Brown', house_id: 1},
  { fname: 'Ritchie', lname: 'Coote', house_id: 1},
  { fname: 'Colin', lname: 'Creevey', house_id: 1},
  { fname: 'Dennis', lname: 'Creevey', house_id: 1},
  { fname: 'Albus', lname: 'Dumbledore', house_id: 1},
  { fname: 'Seamus', lname: 'Finnigan', house_id: 1},
  { fname: 'Hermione', lname: 'Granger', house_id: 1},
  { fname: 'Rubeus', lname: 'Hagrid', house_id: 1},
  { fname: 'Angelina', lname: 'Johnson', house_id: 1},
  { fname: 'Lee', lname: 'Jordan', house_id: 1},
  { fname: 'Andrew', lname: 'Kirke', house_id: 1},
  { fname: 'Neville', lname: 'Longbottom', house_id: 1},
  { fname: 'Remus', lname: 'Lupin', house_id: 1},
  { fname: 'Natalie', lname: 'McDonald', house_id: 1},
  { fname: 'Mary', lname: 'Macdonald', house_id: 1},
  { fname: 'Minerva', lname: 'McGonagall', house_id: 1},
  { fname: 'Cormac', lname: 'McLaggen', house_id: 1},
  { fname: 'Parvati', lname: 'Patil', house_id: 1},
  { fname: 'Jimmy', lname: 'Peakes', house_id: 1},
  { fname: 'Peter', lname: 'Pettigrew', house_id: 1},
  { fname: 'Harry', lname: 'Potter', house_id: 1},
  { fname: 'James', lname: 'Potter', house_id: 1},
  { fname: 'Lily', lname: 'Potter', house_id: 1},
  { fname: 'Demelza', lname: 'Robins', house_id: 1},
  { fname: 'Jack', lname: 'Sloper', house_id: 1},
  { fname: 'Alicia', lname: 'Spinnet', house_id: 1},
  { fname: 'Dean', lname: 'Thomas', house_id: 1},
  { fname: 'Romilda', lname: 'Vane', house_id: 1},
  { fname: 'Arthur', lname: 'Weasley', house_id: 1},
  { fname: 'Bill', lname: 'Weasley', house_id: 1},
  { fname: 'Charlie', lname: 'Weasley', house_id: 1},
  { fname: 'Fred', lname: 'Weasley', house_id: 1},
  { fname: 'George', lname: 'Weasley', house_id: 1},
  { fname: 'Ginny', lname: 'Weasley', house_id: 1},
  { fname: 'Molly', lname: 'Weasley', house_id: 1},
  { fname: 'Percy', lname: 'Weasley', house_id: 1},
  { fname: 'Ron', lname: 'Weasley', house_id: 1},
  { fname: 'Oliver', lname: 'Wood', house_id: 1},
  { fname: 'Hannah', lname: 'Abbott', house_id: 2},
  { fname: 'Susan', lname: 'Bones', house_id: 2},
  { fname: 'Eleanor', lname: 'Branstone', house_id: 2},
  { fname: 'Owen', lname: 'Cauldwell', house_id: 2},
  { fname: 'Cedric', lname: 'Diggory', house_id: 2},
  { fname: 'Justin', lname: 'Finch-Fletchley', house_id: 2},
  { fname: 'Ernie', lname: 'Macmillan', house_id: 2},
  { fname: 'Laura', lname: 'Madley', house_id: 2},
  { fname: 'Eloise', lname: 'Midgeon', house_id: 2},
  { fname: 'Zacharias', lname: 'Smith', house_id: 2},
  { fname: 'Pomona', lname: 'Sprout', house_id: 2},
  { fname: 'Nymphadora', lname: 'Tonks', house_id: 2},
  { fname: 'Kevin', lname: 'Whitby', house_id: 2},
  { fname: 'Rose', lname: 'Zeller', house_id: 2},
  { fname: 'Stewart', lname: 'Ackerley', house_id: 3},
  { fname: 'Marcus', lname: 'Belby', house_id: 3},
  { fname: 'Terry', lname: 'Boot', house_id: 3},
  { fname: 'Mandy', lname: 'Brocklehurst', house_id: 3},
  { fname: 'Cho', lname: 'Chang', house_id: 3},
  { fname: 'Eddie', lname: 'Carmichael', house_id: 3},
  { fname: 'Penelope', lname: 'Clearwater', house_id: 3},
  { fname: 'Michael', lname: 'Corner', house_id: 3},
  { fname: 'Roger', lname: 'Davies', house_id: 3},
  { fname: 'Marietta', lname: 'Edgecombe', house_id: 3},
  { fname: 'S.', lname: 'Fawcett', house_id: 3},
  { fname: 'Filius', lname: 'Flitwick', house_id: 3},
  { fname: 'Anthony', lname: 'Goldstein', house_id: 3},
  { fname: 'Luna', lname: 'Lovegood', house_id: 3},
  { fname: 'Padma', lname: 'Patil', house_id: 3},
  { fname: 'Orla', lname: 'Quirke', house_id: 3},
  { fname: 'Lisa', lname: 'Turpin', house_id: 3},
  { fname: 'Malcolm', lname: 'Baddock', house_id: 4},
  { fname: 'Regulus', lname: 'Black', house_id: 4},
  { fname: 'Miles', lname: 'Bletchley', house_id: 4},
  { fname: 'Millicent', lname: 'Bulstrode', house_id: 4},
  { fname: 'Vincent', lname: 'Crabbe', house_id: 4},
  { fname: 'Marcus', lname: 'Flint', house_id: 4},
  { fname: 'Gregory', lname: 'Goyle', house_id: 4},
  { fname: 'Terence', lname: 'Higgs', house_id: 4},
  { fname: 'Bellatrix', lname: 'Lestrange', house_id: 4},
  { fname: 'Rabastan', lname: 'Lestrange', house_id: 4},
  { fname: 'Rodolphus', lname: 'Lestrange', house_id: 4},
  { fname: 'Abraxas', lname: 'Malfoy', house_id: 4},
  { fname: 'Draco', lname: 'Malfoy', house_id: 4},
  { fname: 'Lucius', lname: 'Malfoy', house_id: 4},
  { fname: 'Narcissa', lname: 'Malfoy', house_id: 4},
  { fname: 'Theodore', lname: 'Nott', house_id: 4},
  { fname: 'Pansy', lname: 'Parkinson', house_id: 4},
  { fname: 'Graham', lname: 'Pritchard', house_id: 4},
  { fname: 'Adrian', lname: 'Pucey', house_id: 4},
  { fname: 'Tom', lname: 'Riddle', house_id: 4},
  { fname: 'Horace', lname: 'Slughorn', house_id: 4},
  { fname: 'Severus', lname: 'Snape', house_id: 4},
  { fname: 'Blaise', lname: 'Zabini', house_id: 4},
  { fname: 'Godric', lname: 'Gryffindor', house_id: 1},
  { fname: 'Helga', lname: 'Hufflepuff', house_id: 2},
  { fname: 'Rowena', lname: 'Ravenclaw', house_id: 3},
  { fname: 'Salazar', lname: 'Slytherin', house_id: 4}
]
def get_img( fname, lname)
  data = HTTParty.get "http://harrypotter.wikia.com/api.php?action=imageserving&format=json&wisTitle=#{fname}_#{lname}"
  data["image"]["imageserving"] || "http://images.clipartpanda.com/question-mark-black-and-white-Icon-round-Question_mark.jpg"
end

file = File.new "potter_seed.sql", "w"

potter_chars.each do |character|
  img_url = get_img character[:fname], character[:lname]
  command = "( '#{character[:fname]}', '#{character[:lname]}', '#{img_url}', #{character[:house_id]} )\n"
  file.write command
end
  #( fname, lname, houseid, img_url )
